<a href="https://colab.research.google.com/github/ValentinaBykova/neuron/blob/master/lab2/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота №2
## студентки КН-31, Бикової Валентини
## Тема: TensorFlow



# Завдання 2


## Знати різні способи створення тензорів

In [14]:
import numpy as np
import tensorflow as tf

tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [15]:
import numpy as np
import tensorflow as tf

print(tf.random.Generator.from_seed(42).normal(shape=(3,2)))

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)


## Створити набір даних із заданим розподілом (розподіл та розмір за власним рішенням), визначити його властивості (shape, rank, size, axis)

In [19]:
import numpy as np
import tensorflow as tf

tensor = tf.Variable([
                   [3, 1, 6, 9],
                   [11, 0, 21, 2],
                   [4, 10, 15, 5]
])

print(tensor.shape)
print(tf.rank(tensor))
print(tf.size(tensor))
print(tf.expand_dims(tensor, axis=-1))

(3, 4)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(
[[[ 3]
  [ 1]
  [ 6]
  [ 9]]

 [[11]
  [ 0]
  [21]
  [ 2]]

 [[ 4]
  [10]
  [15]
  [ 5]]], shape=(3, 4, 1), dtype=int32)


## Продемонструвати основні математичні операції над тензорами

In [23]:
import numpy as np
import tensorflow as tf

tensor = tf.Variable([
                   [3, 1, 6, 9],
                   [11, 0, 21, 2],
                   [4, 10, 15, 5]
])

print(tensor+10)
print(tensor-10)
print(tensor*10)
print(tensor@tf.reshape(tensor, shape=(4, 3)))

tf.Tensor(
[[13 11 16 19]
 [21 10 31 12]
 [14 20 25 15]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[ -7  -9  -4  -1]
 [  1 -10  11  -8]
 [ -6   0   5  -5]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[ 30  10  60  90]
 [110   0 210  20]
 [ 40 100 150  50]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[234 161  87]
 [494  83 160]
 [467 219 109]], shape=(3, 3), dtype=int32)


## Провести CRUD операції над даними, reshape, інтеграцію з np.array, pd.DataFrame)

In [33]:
import numpy as np
import tensorflow as tf
import pandas as pd

tensor = tf.Variable([
                   [3, 1, 6, 9],
                   [11, 0, 21, 2],
                   [4, 10, 15, 5]
]) 

tf.compat.v1.assign(tensor[2], [1, 2, 9, 5])
print(tf.slice(tensor, [1, 0], [1, 4]))
print(tf.reshape(tensor, shape=(4, 3)))
print(tf.Variable(np.array([[3, 1], [15, 5]])))
print(tf.Variable(pd.DataFrame([[11, 0], [4, 10]])))

tf.Tensor([[11  0 21  2]], shape=(1, 4), dtype=int32)
tf.Tensor(
[[ 3  1  6]
 [ 9 11  0]
 [21  2  1]
 [ 2  9  5]], shape=(4, 3), dtype=int32)
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int64, numpy=
array([[ 3,  1],
       [15,  5]])>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int64, numpy=
array([[11,  0],
       [ 4, 10]])>
